# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see:
# https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions


name: pre-commit


on:
  push:
    branches: [ $default-branch , "main" , "dev" ]
  pull_request:
    branches: [ $default-branch , "main" ]

permissions:
  contents: read


jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - name: Install dependencies
      run: |
        pip install flake8
    - uses: pre-commit/action@v3.0.1
